packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@parcel/watcher'
  - '@prisma/engines'
  - bcrypt
  - esbuild
  - less
  - msw
  - nx
  - prisma
  - sharp
  - unrs-resolver
