name: CI-Check

on:
  push:
    branches: [main]
    paths-ignore: ['**.md']
  pull_request:
    branches: [develop, main]
    types: [opened, synchronize]
  workflow_dispatch:

jobs:
  check-project:
    runs-on: ubuntu-latest
    steps:
      - name: Copy repository code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Run Eslint
        run: pnpm run lint

      - name: typeScript Check
        run: pnpm run type-check

      - name: Build Project
        run: pnpm run build
